base:
  project: mlops-project
  random_state: 42
  target_col: sentiment

data_source:
  s3_source: data_given/sentiment_analysis.csv

load_data:
  raw_dataset_csv: data/raw/sentiment_analysis.csv

split_data:
  train_path: data/processed/train_sentiment_analysis.csv
  test_path: data/processed/test_sentiment_analysis.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.10
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.h5